'use client';

import { useEffect, useState } from 'react';

type Locale = 'es' | 'en';

const focus = {
  es: ['Sistemas embebidos', 'Firmware', 'Hardware', 'Linux', 'Programación de sistemas'],
  en: ['Embedded systems', 'Firmware', 'Hardware', 'Linux', 'Systems programming'],
};

const projectsEs = [
  { id: '01', name: 'MicroPythonOS', status: 'Experimental avanzado', stack: 'ESP32-S3 · MicroPython · LVGL', label: 'Arquitectura distribuida', visual: 'micro', image: '/projects/micropythonos.png', intro: 'Una consola modular distribuida entre varios microcontroladores.', body: 'Una placa funciona como CPU principal y otra como PPU/southbridge para gráficos y periféricos. Las conecta un protocolo SPI propio con sincronización, longitud y checksum.', challenge: 'Coordinar máquinas de estados, buffers, límites de transferencia, PSRAM y portabilidad entre distintas placas.', built: 'Un sistema dividido entre una CPU principal y una segunda placa dedicada a gráficos, entrada y periféricos. El prototipo utiliza una pantalla ILI9488 de 480×320, touch XPT2046 y una interfaz construida con LVGL.', why: 'Quería explorar hasta dónde puede crecer un sistema formado por microcontroladores cuando la arquitectura, en lugar del hardware, se convierte en el centro del diseño.', hardware: ['ESP32-S3 N16R8', 'ESP32 WROOM', 'ILI9488', 'XPT2046', '8 MB PSRAM'], software: ['MicroPython', 'C/C++', 'LVGL', 'SPI', 'Máquinas de estados'], learned: 'Diseñar el framing de un protocolo, recuperarse de paquetes incompletos y separar responsabilidades son tan importantes como conseguir que la primera demo funcione.' },
  { id: '02', name: 'MetaDeck', status: 'En desarrollo activo', stack: 'ESP32 · C/C++ · ESP-IDF', label: 'Firmware modular', visual: 'metadeck', image: '/projects/metadeck.png', intro: 'Un pequeño dispositivo que evolucionó hasta convertirse en una plataforma de aplicaciones embebidas.', body: 'Un core desacoplado gestiona eventos, navegación, rendering y comunicación; encima viven apps intercambiables para música, monitorización del PC y controles multimedia.', challenge: 'Diseñar una arquitectura extensible dentro de los límites de memoria, interfaz y procesamiento de un microcontrolador.', built: 'Un runtime embebido que desacopla LCD, encoder, botones y comunicación de las aplicaciones. Music Mixer, Hardware Monitor y los controles multimedia comparten navegación y rendering.', why: 'El primer prototipo solo controlaba música. Convertirlo en una plataforma permite añadir nuevas herramientas sin reescribir el firmware alrededor de una única función.', hardware: ['ESP32', 'LCD', 'Encoder rotatorio', 'Botones'], software: ['C/C++', 'Arduino / ESP-IDF', 'Event loop', 'Protocolo serie'], learned: 'Una interfaz pequeña obliga a definir muy bien el modelo de eventos, el foco y la propiedad de cada pantalla.' },
  { id: '03', name: 'Cyberdeck', status: 'En construcción', stack: 'Raspberry Pi · Linux · DC-DC', label: 'Hardware integrado', visual: 'cyberdeck', image: '/projects/cyberdeck.png', intro: 'Un ordenador portátil compacto para programar, experimentar y diagnosticar hardware.', body: 'Integra una Raspberry Pi, teclado, refrigeración y una cadena de alimentación diseñada alrededor de baterías de herramienta y conversión de 21 V a 5 V.', challenge: 'Equilibrar autonomía, entrega de potencia, temperatura y montaje físico en un sistema realmente transportable.', built: 'Una arquitectura física y eléctrica para reunir ordenador, pantalla, teclado, refrigeración y acceso a hardware en una carcasa portátil. La BOM documenta coste, estado y función de cada componente.', why: 'Buscaba una estación personal que pudiera viajar al banco de trabajo y servir tanto para programar como para interactuar con otros dispositivos.', hardware: ['Raspberry Pi', 'Batería de 21 V', 'Conversor buck', 'Teclado integrado'], software: ['Linux', 'Herramientas shell', 'Networking', 'BOM workflow'], learned: 'En un producto portátil la alimentación, la disipación y la distribución física deben diseñarse juntas desde el principio.' },
  { id: '04', name: 'Portable Wii', status: 'Proyecto hardware', stack: 'Nintendo Wii · Custom power · Soldering', label: 'Hardware hacking', visual: 'wii', image: '/projects/portable-wii.png', intro: 'Hardware real de Nintendo Wii transformado en una consola portátil.', body: 'Modificación de placa, alimentación personalizada, refrigeración y cableado de señales con componentes especializados como RVL-PMS-Lite y PMS-PD.', challenge: 'Diagnosticar fallos eléctricos y entender la distribución de voltajes, el consumo y las modificaciones críticas de la placa.', built: 'Un sistema portátil basado en una placa Wii real, con power management, cableado personalizado, modificación U10 y refrigeración específica para CPU y GPU.', why: 'Es un ejercicio completo de ingeniería inversa e integración: conservar la compatibilidad del hardware original mientras cambia por completo su formato físico.', hardware: ['Placa Wii', 'RVL-PMS-Lite', 'PMS-PD', 'Cableado 22/33 AWG'], software: ['RVLoader', 'Diagnóstico eléctrico', 'Power budgeting', 'Planificación térmica'], learned: 'Perder una placa y una PMS-Lite por problemas eléctricos convirtió la protección, la medición previa y la validación por etapas en requisitos del diseño.' },
  { id: '05', name: 'PMS2 Emulator', status: 'Prototipo de firmware', stack: 'RP2040 · C++ · Pico SDK · I²C', label: 'Ingeniería inversa', visual: 'pms', image: '/projects/pms2-emulator.png', intro: 'Un RP2040 que emula la interfaz de gestión de energía esperada por RVLoader.', body: 'El firmware reproduce comandos de una PMS2 y expone voltaje, carga, batería, temperatura y estado del cargador a través de I²C.', challenge: 'Reconstruir el comportamiento de un protocolo hardware existente y hacerlo fiable dentro de un proyecto C++ depurable.', built: 'Un proyecto estructurado con Pico SDK y CMake donde el RP2040 responde como dispositivo I²C y reproduce los registros que consulta el software de la Wii.', why: 'Emular la placa permite comprender el contrato real entre RVLoader y el sistema de alimentación, además de abrir la puerta a hardware propio.', hardware: ['RP2040 / Pico', 'Bus I²C', 'Sensores de potencia'], software: ['C++', 'Pico SDK', 'CMake', 'OpenOCD'], learned: 'La compatibilidad depende de replicar tiempos, estados y casos límite, no solo de devolver el valor correcto para cada comando.' },
  { id: '06', name: 'Linux on Tab S9 FE', status: 'Investigación', stack: 'ARM64 · Linux kernel · Device Tree', label: 'Platform bring-up', visual: 'linux', image: '/projects/linux-tab.png', intro: 'Investigar un port de Linux nativo para una tablet Samsung, más allá de ejecutar Linux dentro de Android.', body: 'El alcance recorre la cadena completa: kernel, device tree, boot, initramfs, root filesystem y bring-up progresivo de pantalla, touch, USB, red y energía.', challenge: 'Convertir el código disponible del kernel Android en una plataforma Linux utilizable pese a los drivers propietarios.', built: 'Un plan de bring-up basado en el kernel android_kernel_samsung_s5e8835, separando el arranque mínimo de la habilitación gradual de periféricos.', why: 'Una tablet moderna concentra muchos de los retos más interesantes de Linux sobre ARM: boot chain, device trees, firmware y controladores específicos.', hardware: ['Samsung S5E8835', 'Tablet ARM64', 'Pantalla táctil', 'USB / wireless'], software: ['Linux kernel', 'Device Tree', 'Initramfs', 'Root filesystem'], learned: 'Un port viable necesita hitos pequeños: consola temprana, almacenamiento, pantalla y entrada antes de abordar GPU, audio o power management.' },
];

const projectsEn = [
  { ...projectsEs[0], status: 'Advanced experiment', label: 'Distributed architecture', intro: 'A modular console distributed across multiple microcontrollers.', body: 'One board acts as the main CPU while another works as a PPU/southbridge for graphics and peripherals. A custom SPI protocol connects them with synchronization, length and checksum fields.', challenge: 'Coordinating state machines, buffers, transfer limits, PSRAM and portability across different boards.', built: 'A system split between a main CPU and a second board dedicated to graphics, input and peripherals. The prototype uses a 480×320 ILI9488 display, XPT2046 touch and an LVGL interface.', why: 'I wanted to explore how far a microcontroller-based system can grow when architecture, rather than a single hardware feature, becomes the center of the design.', hardware: ['ESP32-S3 N16R8', 'ESP32 WROOM', 'ILI9488', 'XPT2046', '8 MB PSRAM'], software: ['MicroPython', 'C/C++', 'LVGL', 'SPI', 'State machines'], learned: 'Protocol framing, recovery from incomplete packets and clear responsibility boundaries matter as much as getting the first demo to run.' },
  { ...projectsEs[1], status: 'Active development', label: 'Modular firmware', intro: 'A small device that evolved into an embedded application platform.', body: 'A decoupled core handles events, navigation, rendering and communication; interchangeable apps sit on top for music, PC monitoring and media controls.', challenge: 'Designing an extensible architecture within a microcontroller’s memory, interface and processing constraints.', built: 'An embedded runtime that separates the LCD, encoder, buttons and communications from individual applications. Music Mixer, Hardware Monitor and media controls share navigation and rendering.', why: 'The first prototype only controlled music. Turning it into a platform makes it possible to add tools without rewriting the firmware around a single purpose.', hardware: ['ESP32', 'LCD', 'Rotary encoder', 'Buttons'], software: ['C/C++', 'Arduino / ESP-IDF', 'Event loop', 'Serial protocol'], learned: 'A small interface forces precise decisions about the event model, focus and ownership of every screen.' },
  { ...projectsEs[2], status: 'Under construction', label: 'Integrated hardware', intro: 'A compact portable computer for programming, experimenting and diagnosing hardware.', body: 'It integrates a Raspberry Pi, keyboard, cooling and a power chain built around tool batteries and 21 V to 5 V conversion.', challenge: 'Balancing runtime, power delivery, temperature and physical assembly in a genuinely portable system.', built: 'A physical and electrical architecture that combines a computer, display, keyboard, cooling and hardware access in a portable enclosure. A full BOM tracks the cost, state and purpose of each component.', why: 'I wanted a personal workstation that could travel to the workbench and work equally well for programming and interacting with other devices.', hardware: ['Raspberry Pi', '21 V battery', 'Buck converter', 'Integrated keyboard'], software: ['Linux', 'Shell tools', 'Networking', 'BOM workflow'], learned: 'In a portable product, power, thermal management and physical distribution have to be designed together from the start.' },
  { ...projectsEs[3], status: 'Hardware project', label: 'Hardware hacking', intro: 'Real Nintendo Wii hardware transformed into a portable console.', body: 'Board modification, custom power, cooling and signal wiring using specialized components such as RVL-PMS-Lite and PMS-PD.', challenge: 'Diagnosing electrical failures and understanding voltage distribution, consumption and critical board modifications.', built: 'A portable system based on a real Wii motherboard, with power management, custom wiring, a U10 modification and dedicated CPU/GPU cooling.', why: 'It is a complete reverse-engineering and integration exercise: preserving compatibility with the original hardware while radically changing its physical form.', hardware: ['Wii motherboard', 'RVL-PMS-Lite', 'PMS-PD', '22/33 AWG wiring'], software: ['RVLoader', 'Electrical diagnosis', 'Power budgeting', 'Thermal planning'], learned: 'Losing a motherboard and a PMS-Lite to electrical problems turned protection, pre-measurement and staged validation into core design requirements.' },
  { ...projectsEs[4], status: 'Firmware prototype', label: 'Reverse engineering', intro: 'An RP2040 that emulates the power-management interface expected by RVLoader.', body: 'The firmware reproduces PMS2 commands and exposes battery voltage, charge, percentage, temperature and charger status over I²C.', challenge: 'Reconstructing the behavior of an existing hardware protocol and making it reliable inside a debuggable C++ project.', built: 'A structured Pico SDK and CMake project where the RP2040 responds as an I²C device and reproduces the registers queried by the Wii software.', why: 'Emulating the board reveals the real contract between RVLoader and the power system while opening a path toward custom hardware.', hardware: ['RP2040 / Pico', 'I²C bus', 'Power sensors'], software: ['C++', 'Pico SDK', 'CMake', 'OpenOCD'], learned: 'Compatibility depends on reproducing timing, states and edge cases—not merely returning the right value for each command.' },
  { ...projectsEs[5], status: 'Research', label: 'Platform bring-up', intro: 'Researching a native Linux port for a Samsung tablet, beyond running Linux inside Android.', body: 'The scope covers the full chain: kernel, device tree, boot, initramfs, root filesystem and progressive bring-up of display, touch, USB, networking and power.', challenge: 'Turning the available Android kernel sources into a usable Linux platform despite proprietary drivers.', built: 'A bring-up plan based on android_kernel_samsung_s5e8835, separating minimum boot from the gradual enablement of each peripheral.', why: 'A modern tablet concentrates many of the most interesting ARM Linux challenges: boot chain, device trees, firmware and device-specific drivers.', hardware: ['Samsung S5E8835', 'ARM64 tablet', 'Touch display', 'USB / wireless'], software: ['Linux kernel', 'Device Tree', 'Initramfs', 'Root filesystem'], learned: 'A viable port needs small milestones: early console, storage, display and input before approaching GPU, audio or power management.' },
];

const experiments = {
  es: [['Galileo Edge Computer', 'Embedded Linux · MQTT · MCU nodes'], ['Herramienta de debugging embedded', 'UART · SPI · I²C · GPIO'], ['Grafos y algoritmos', 'C++ · BFS · MST · Floyd'], ['Simulador de memoria', 'C · Linux · Docker'], ['Concurrencia y scheduling', 'pthreads · fork · Round Robin'], ['Datos geográficos', 'Python · Excel · Nominatim'], ['Electrónica digital', 'VHDL · Quartus · RTL'], ['Portales 2D', 'Godot · GDScript · Transformaciones']],
  en: [['Galileo Edge Computer', 'Embedded Linux · MQTT · MCU nodes'], ['Embedded debugging tool', 'UART · SPI · I²C · GPIO'], ['Graphs and algorithms', 'C++ · BFS · MST · Floyd'], ['Memory simulator', 'C · Linux · Docker'], ['Concurrency and scheduling', 'pthreads · fork · Round Robin'], ['Geographic data', 'Python · Excel · Nominatim'], ['Digital electronics', 'VHDL · Quartus · RTL'], ['2D portals', 'Godot · GDScript · Transforms']],
};

const copy = {
  es: { projects: 'Proyectos', profile: 'Perfil', experiments: 'Experimentos', available: 'Abierto a oportunidades', heroEyebrow: 'Sistemas embebidos · Hardware hacking', heroA: 'Construyo sistemas', heroB: 'desde abajo.', lede: 'Diseño hardware, firmware y arquitecturas que conectan dispositivos reales con el software que los hace útiles.', explore: 'Explorar proyectos', about: 'Sobre mí', selected: 'Selected engineering', featured: 'Proyectos destacados', featuredText: 'Pulsa cualquier proyecto para abrir su arquitectura, retos, aprendizajes e imágenes.', open: 'Ver case study', profileEye: 'Perfil / 2026', profileA: 'Entre la placa', profileB: 'y el sistema.', aboutLead: 'Soy Mark, estudiante y desarrollador centrado en sistemas embebidos, electrónica y programación de bajo nivel.', aboutP1: 'Me interesa entender el sistema completo: qué ocurre en los pines, cómo viajan los datos, quién gobierna el hardware y qué arquitectura permite convertir todo eso en una herramienta útil.', aboutP2: 'Mis proyectos nacen de preguntas prácticas y suelen acabar cruzando varias disciplinas: diseño de protocolos, firmware, Linux, electrónica de potencia, debugging y experiencia de usuario.', principles: [['Construir para entender', 'Los sistemas complejos dejan de ser cajas negras cuando los llevas al banco de trabajo.'], ['Diseñar por capas', 'Hardware, protocolo y aplicación evolucionan mejor cuando sus límites son explícitos.'], ['Medir, fallar, iterar', 'Cada fallo eléctrico o bug de sincronización se convierte en conocimiento reutilizable.']], toolbox: 'Toolbox', layers: 'Capas con las que trabajo', lab: 'Lab notes', small: 'Experimentos y proyectos pequeños', smallText: 'Trabajo académico, prototipos y conceptos que complementan los casos principales.', next: 'Next system', closingA: 'Del primer bit', closingB: 'al producto final.', closingText: 'Interesado en firmware, embedded Linux, arquitectura de sistemas y retos de hardware que exijan mirar debajo de la abstracción.', back: 'Volver arriba', follow: 'Encuéntrame en', caseStudy: 'Case study', close: 'Cerrar', concept: 'Render conceptual · sustituible por foto real', detail: 'Detalle', sections: ['Qué construí', 'Por qué', 'Reto principal', 'Qué aprendí'], hardware: 'Hardware', software: 'Software / stack', previous: 'Proyecto anterior', nextProject: 'Proyecto siguiente' },
  en: { projects: 'Projects', profile: 'Profile', experiments: 'Experiments', available: 'Open to opportunities', heroEyebrow: 'Embedded systems · Hardware hacking', heroA: 'I build systems', heroB: 'from the bottom up.', lede: 'I design hardware, firmware and architectures that connect real devices to the software that makes them useful.', explore: 'Explore projects', about: 'About me', selected: 'Selected engineering', featured: 'Featured projects', featuredText: 'Select any project to explore its architecture, challenges, lessons and imagery.', open: 'View case study', profileEye: 'Profile / 2026', profileA: 'Between the board', profileB: 'and the system.', aboutLead: 'I’m Mark, a student and developer focused on embedded systems, electronics and low-level programming.', aboutP1: 'I want to understand the complete system: what happens at the pins, how data moves, who controls the hardware and which architecture turns it all into a useful tool.', aboutP2: 'My projects begin with practical questions and usually cross several disciplines: protocol design, firmware, Linux, power electronics, debugging and user experience.', principles: [['Build to understand', 'Complex systems stop being black boxes when you bring them to the workbench.'], ['Design in layers', 'Hardware, protocol and application evolve better when their boundaries are explicit.'], ['Measure, fail, iterate', 'Every electrical failure or synchronization bug becomes reusable knowledge.']], toolbox: 'Toolbox', layers: 'Layers I work across', lab: 'Lab notes', small: 'Experiments and smaller projects', smallText: 'Academic work, prototypes and concepts that complement the main case studies.', next: 'Next system', closingA: 'From the first bit', closingB: 'to the final product.', closingText: 'Interested in firmware, embedded Linux, systems architecture and hardware challenges that demand looking beneath the abstraction.', back: 'Back to top', follow: 'Find me on', caseStudy: 'Case study', close: 'Close', concept: 'Concept render · replaceable with a real photo', detail: 'Detail', sections: ['What I built', 'Why I built it', 'Main challenge', 'What I learned'], hardware: 'Hardware', software: 'Software / stack', previous: 'Previous project', nextProject: 'Next project' },
};

type Project = (typeof projectsEs)[number];

function ProjectVisual({ type }: { type: string }) {
  if (type === 'micro') return <div className="architecture compact"><div className="chip"><small>MAIN</small><b>CPU</b><span>ESP32-S3</span></div><div className="bus"><span>SPI</span></div><div className="chip accent"><small>I/O</small><b>PPU</b><span>ESP32</span></div></div>;
  if (type === 'metadeck') return <div className="app-grid"><span>MUSIC</span><span>STATS</span><span>MEDIA</span><span>+</span></div>;
  if (type === 'cyberdeck') return <div className="power-flow"><b>21V</b><i /><strong>BUCK</strong><i /><b>5V</b><small>POWER RAIL / STABLE</small></div>;
  if (type === 'wii') return <div className="board"><span>CPU</span><span>GPU</span><span>PMS</span><i /><i /><i /><i /></div>;
  if (type === 'pms') return <div className="packet"><small>I²C PACKET</small><span>ADDR</span><span>CMD</span><span>DATA</span><span>ACK</span><b>0x52</b></div>;
  return <div className="boot-log"><span>&gt; boot arm64 kernel</span><span>&gt; load device tree</span><span>&gt; mount rootfs</span><span className="ok">[ OK ] init hardware</span><i /></div>;
}

function ProjectModal({ project, locale, onClose, onPrevious, onNext }: { project: Project; locale: Locale; onClose: () => void; onPrevious: () => void; onNext: () => void }) {
  const c = copy[locale];
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowLeft') onPrevious(); if (event.key === 'ArrowRight') onNext(); };
    document.addEventListener('keydown', onKey); document.body.classList.add('modal-open');
    return () => { document.removeEventListener('keydown', onKey); document.body.classList.remove('modal-open'); };
  }, [onClose, onPrevious, onNext]);
  const sectionText = [project.built, project.why, project.challenge, project.learned];
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title"><button className="modal-close" type="button" onClick={onClose} aria-label={c.close} autoFocus>ESC <b>×</b></button><div className="modal-head"><div><p className="eyebrow">{c.caseStudy} / {project.id}</p><h2 id="project-modal-title">{project.name}</h2><p>{project.intro}</p></div><div className="modal-status"><span>{project.status}</span><span>{project.stack}</span></div></div><div className="project-gallery"><figure className="gallery-main"><img src={project.image} alt={`${locale === 'es' ? 'Render conceptual de' : 'Concept render of'} ${project.name}`} /><figcaption>{c.concept}</figcaption></figure><figure className="gallery-crop crop-a"><img src={project.image} alt="" /><figcaption>{c.detail} / 01</figcaption></figure><figure className="gallery-crop crop-b"><img src={project.image} alt="" /><figcaption>{c.detail} / 02</figcaption></figure></div><div className="modal-content">{c.sections.map((title, index) => <div key={title}><span>0{index + 1} / {title}</span><p>{sectionText[index]}</p></div>)}</div><div className="modal-stack"><div><span>{c.hardware}</span>{project.hardware.map(item => <b key={item}>{item}</b>)}</div><div><span>{c.software}</span>{project.software.map(item => <b key={item}>{item}</b>)}</div></div><div className="modal-pagination"><button type="button" onClick={onPrevious}><span>←</span>{c.previous}</button><b>{project.id} / 06</b><button type="button" onClick={onNext}>{c.nextProject}<span>→</span></button></div></section></div>;
}

export default function Home() {
  const [locale, setLocale] = useState<Locale>('es');
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const [progress, setProgress] = useState(0);
  const [activeSection, setActiveSection] = useState('');
  const projects = locale === 'es' ? projectsEs : projectsEn;
  const c = copy[locale];

  useEffect(() => {
    const queryLocale = new URLSearchParams(window.location.search).get('lang');
    const savedLocale = window.localStorage.getItem('portfolio-language');
    if (queryLocale === 'en' || queryLocale === 'es') setLocale(queryLocale);
    else if (savedLocale === 'en') setLocale('en');
  }, []);

  useEffect(() => {
    document.documentElement.lang = locale;
    document.title = locale === 'es' ? 'Mark Piazuelo — Sistemas embebidos y hardware' : 'Mark Piazuelo — Embedded Systems & Hardware';
    const onScroll = () => { const total = document.documentElement.scrollHeight - window.innerHeight; setProgress(total > 0 ? Math.min(100, (window.scrollY / total) * 100) : 0); };
    onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll);
  }, [locale]);

  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: '-30% 0px -60%' });
    ['work', 'about', 'experiments'].forEach(id => { const element = document.getElementById(id); if (element) observer.observe(element); });
    return () => observer.disconnect();
  }, []);

  const changeLocale = (nextLocale: Locale) => { setLocale(nextLocale); window.localStorage.setItem('portfolio-language', nextLocale); const url = new URL(window.location.href); if (nextLocale === 'en') url.searchParams.set('lang', 'en'); else url.searchParams.delete('lang'); window.history.replaceState({}, '', url); };
  const openWithKeyboard = (event: React.KeyboardEvent, index: number) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setActiveIndex(index); } };
  const previousProject = () => setActiveIndex(index => index === null ? 0 : (index + projects.length - 1) % projects.length);
  const nextProject = () => setActiveIndex(index => index === null ? 0 : (index + 1) % projects.length);
  const lead = projects[0];

  return <main>
    <div className="scroll-progress" style={{ width: `${progress}%` }} />
    <header className="nav-wrap"><nav className="nav shell" aria-label={locale === 'es' ? 'Navegación principal' : 'Main navigation'}><a className="brand" href="#top" aria-label="Home"><span className="brand-mark">MP</span><span>Mark Piazuelo</span></a><div className="nav-links"><a className={activeSection === 'work' ? 'active' : ''} href="#work">{c.projects}</a><a className={activeSection === 'about' ? 'active' : ''} href="#about">{c.profile}</a><a className={activeSection === 'experiments' ? 'active' : ''} href="#experiments">{c.experiments}</a></div><div className="nav-tools"><a className="nav-social" href="https://github.com/Mark19000" target="_blank" rel="noreferrer">GH↗</a><a className="nav-social" href="https://www.linkedin.com/in/mark-piazuelo/" target="_blank" rel="noreferrer">IN↗</a><div className="language-switch" aria-label="Language"><button className={locale === 'es' ? 'active' : ''} type="button" onClick={() => changeLocale('es')}>ES</button><span>/</span><button className={locale === 'en' ? 'active' : ''} type="button" onClick={() => changeLocale('en')}>EN</button></div><span className="status"><i /> {c.available}</span></div></nav></header>

    <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">{c.heroEyebrow}</p><h1>{c.heroA}<br /><em>{c.heroB}</em></h1><p className="lede">{c.lede}</p><div className="hero-actions"><a className="button primary" href="#work">{c.explore} <span>↓</span></a><a className="button secondary" href="#about">{c.about}</a></div></div><div className="system-map" aria-label="System map"><div className="map-head"><span>system_map.log</span><span>ACTIVE</span></div><div className="map-body"><div className="node hot"><small>01</small><strong>HARDWARE</strong><span>ESP32 · RP2040 · ARM</span></div><div className="connector"><span>SPI</span></div><div className="node"><small>02</small><strong>FIRMWARE</strong><span>C/C++ · Drivers · RTOS</span></div><div className="connector"><span>API</span></div><div className="node"><small>03</small><strong>SYSTEM</strong><span>Linux · Protocols · UI</span></div></div><div className="map-foot"><span>latency: low</span><span>layers: 03</span><span>status: building</span></div></div></section>

    <section className="focus-strip"><div className="shell focus-list">{focus[locale].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}</div></section>
    <section className="work shell" id="work"><div className="section-heading"><div><p className="eyebrow">{c.selected}</p><h2>{c.featured}</h2></div><p>{c.featuredText}</p></div><article className="project-card project-lead is-clickable" role="button" tabIndex={0} aria-haspopup="dialog" onClick={() => setActiveIndex(0)} onKeyDown={event => openWithKeyboard(event, 0)}><div className="project-number">{lead.id} / 06</div><div className="project-copy"><div className="project-meta"><span>{lead.status}</span><span>{lead.stack}</span></div><p className="project-label">{lead.label}</p><h3>{lead.name}</h3><p className="project-tagline">{lead.intro}</p><p>{lead.body}</p><span className="project-link">{c.open} <b>↗</b></span></div><div className="project-visual lead-visual"><img src={lead.image} alt="MicroPythonOS" /><span className="concept-badge">Concept render</span></div></article><div className="project-stack">{projects.slice(1).map((project, sliceIndex) => { const index = sliceIndex + 1; return <article className="project-row is-clickable" role="button" tabIndex={0} aria-haspopup="dialog" onClick={() => setActiveIndex(index)} onKeyDown={event => openWithKeyboard(event, index)} key={project.name}><div className="project-number">{project.id} / 06</div><div className="project-copy"><div className="project-meta"><span>{project.status}</span><span>{project.stack}</span></div><p className="project-label">{project.label}</p><h3>{project.name}</h3><p className="project-tagline">{project.intro}</p><p>{project.body}</p><span className="project-link">{c.open} <b>↗</b></span></div><div className={`project-visual ${project.visual}`}><ProjectVisual type={project.visual} /><span className="visual-hover"><img src={project.image} alt={project.name} /></span></div></article>; })}</div></section>

    <section className="about" id="about"><div className="shell about-grid"><div><p className="eyebrow">{c.profileEye}</p><h2>{c.profileA}<br />{c.profileB}</h2></div><div className="about-copy"><p className="about-lede">{c.aboutLead}</p><p>{c.aboutP1}</p><p>{c.aboutP2}</p></div><div className="principles">{c.principles.map(([title, text], index) => <div key={title}><span>0{index + 1}</span><b>{title}</b><p>{text}</p></div>)}</div></div></section>
    <section className="toolbox shell"><div className="section-heading"><div><p className="eyebrow">{c.toolbox}</p><h2>{c.layers}</h2></div></div><div className="tool-grid"><div><span>01</span><h3>Hardware</h3><p>ESP32 / ESP32-S3<br />RP2040 / Raspberry Pi<br />Arduino · ARM64</p></div><div><span>02</span><h3>Interfaces</h3><p>SPI · I²C · UART<br />PWM · ADC · GPIO<br />Custom protocols</p></div><div><span>03</span><h3>Software</h3><p>C · C++ · Python<br />ESP-IDF · Pico SDK<br />MicroPython · LVGL</p></div><div><span>04</span><h3>Systems</h3><p>Linux · CMake · Git<br />OpenOCD · Docker<br />VHDL · Quartus</p></div></div></section>
    <section className="experiments shell" id="experiments"><div className="section-heading"><div><p className="eyebrow">{c.lab}</p><h2>{c.small}</h2></div><p>{c.smallText}</p></div><div className="experiment-list">{experiments[locale].map(([name, stack], index) => <div key={name}><span>{String(index + 1).padStart(2, '0')}</span><h3>{name}</h3><p>{stack}</p><i>↗</i></div>)}</div></section>

    <section className="social-band"><div className="shell"><span>{c.follow}</span><a href="https://github.com/Mark19000" target="_blank" rel="noreferrer"><b>GitHub</b><i>↗</i></a><a href="https://www.linkedin.com/in/mark-piazuelo/" target="_blank" rel="noreferrer"><b>LinkedIn</b><i>↗</i></a></div></section>
    <section className="closing shell"><p className="eyebrow">{c.next}</p><h2>{c.closingA}<br />{c.closingB}</h2><p>{c.closingText}</p><div className="closing-actions"><a className="button primary" href="https://www.linkedin.com/in/mark-piazuelo/" target="_blank" rel="noreferrer">LinkedIn <span>↗</span></a><a className="button secondary" href="#top">{c.back} <span>↑</span></a></div></section><footer className="footer shell"><span>© 2026 Mark Piazuelo</span><span>Embedded systems · Barcelona, ES</span><a href="https://github.com/Mark19000" target="_blank" rel="noreferrer">github.com/Mark19000 ↗</a></footer>
    {activeIndex !== null && <ProjectModal project={projects[activeIndex]} locale={locale} onClose={() => setActiveIndex(null)} onPrevious={previousProject} onNext={nextProject} />}
  </main>;
}
