'use client';

import { useEffect, useState } from 'react';
import { getProjects, type Locale, type Project } from '@/content/projects';


const focus = {
  es: ['Sistemas embebidos', 'Firmware', 'Hardware', 'Linux', 'Programación de sistemas'],
  en: ['Embedded systems', 'Firmware', 'Hardware', 'Linux', 'Systems programming'],
};


const experiments = {
  es: [['Herramienta de debugging embedded', 'UART · SPI · I²C · GPIO'], ['Grafos y algoritmos', 'C++ · BFS · MST · Floyd'], ['Simulador de memoria', 'C · Linux · Docker'], ['Concurrencia y scheduling', 'pthreads · fork · Round Robin'], ['Datos geográficos', 'Python · Excel · Nominatim'], ['Electrónica digital', 'VHDL · Quartus · RTL'], ['Portales 2D', 'Godot · GDScript · Transformaciones']],
  en: [['Embedded debugging tool', 'UART · SPI · I²C · GPIO'], ['Graphs and algorithms', 'C++ · BFS · MST · Floyd'], ['Memory simulator', 'C · Linux · Docker'], ['Concurrency and scheduling', 'pthreads · fork · Round Robin'], ['Geographic data', 'Python · Excel · Nominatim'], ['Digital electronics', 'VHDL · Quartus · RTL'], ['2D portals', 'Godot · GDScript · Transforms']],
};

const copy = {
  es: { projects: 'Proyectos', profile: 'Perfil', experiments: 'Experimentos', available: 'Abierto a oportunidades', heroEyebrow: 'Sistemas embebidos · Hardware hacking', heroA: 'Construyo sistemas', heroB: 'desde abajo.', lede: 'Diseño hardware, firmware y arquitecturas que conectan dispositivos reales con el software que los hace útiles.', explore: 'Explorar proyectos', about: 'Sobre mí', selected: 'Selected engineering', featured: 'Proyectos destacados', featuredText: 'Pulsa cualquier proyecto para abrir su arquitectura, retos, aprendizajes e imágenes.', open: 'Ver case study', profileEye: 'Perfil / 2026', profileA: 'Entre la placa', profileB: 'y el sistema.', aboutLead: 'Soy Mark, estudiante y desarrollador centrado en sistemas embebidos, electrónica y programación de bajo nivel.', aboutP1: 'Me interesa entender el sistema completo: qué ocurre en los pines, cómo viajan los datos, quién gobierna el hardware y qué arquitectura permite convertir todo eso en una herramienta útil.', aboutP2: 'Mis proyectos nacen de preguntas prácticas y suelen acabar cruzando varias disciplinas: diseño de protocolos, firmware, Linux, electrónica de potencia, debugging y experiencia de usuario.', principles: [['Construir para entender', 'Los sistemas complejos dejan de ser cajas negras cuando los llevas al banco de trabajo.'], ['Diseñar por capas', 'Hardware, protocolo y aplicación evolucionan mejor cuando sus límites son explícitos.'], ['Medir, fallar, iterar', 'Cada fallo eléctrico o bug de sincronización se convierte en conocimiento reutilizable.']], toolbox: 'Toolbox', layers: 'Capas con las que trabajo', lab: 'Lab notes', small: 'Experimentos y proyectos pequeños', smallText: 'Trabajo académico, prototipos y conceptos que complementan los casos principales.', next: 'Next system', closingA: 'Del primer bit', closingB: 'al producto final.', closingText: 'Interesado en firmware, embedded Linux, arquitectura de sistemas y retos de hardware que exijan mirar debajo de la abstracción.', back: 'Volver arriba', follow: 'Encuéntrame en', caseStudy: 'Case study', close: 'Cerrar', concept: 'Render conceptual · sustituible por foto real', detail: 'Detalle', sections: ['Qué construí', 'Por qué', 'Reto principal', 'Qué aprendí'], hardware: 'Hardware', software: 'Software / stack', previous: 'Proyecto anterior', nextProject: 'Proyecto siguiente' },
  en: { projects: 'Projects', profile: 'Profile', experiments: 'Experiments', available: 'Open to opportunities', heroEyebrow: 'Embedded systems · Hardware hacking', heroA: 'I build systems', heroB: 'from the bottom up.', lede: 'I design hardware, firmware and architectures that connect real devices to the software that makes them useful.', explore: 'Explore projects', about: 'About me', selected: 'Selected engineering', featured: 'Featured projects', featuredText: 'Select any project to explore its architecture, challenges, lessons and imagery.', open: 'View case study', profileEye: 'Profile / 2026', profileA: 'Between the board', profileB: 'and the system.', aboutLead: 'I’m Mark, a student and developer focused on embedded systems, electronics and low-level programming.', aboutP1: 'I want to understand the complete system: what happens at the pins, how data moves, who controls the hardware and which architecture turns it all into a useful tool.', aboutP2: 'My projects begin with practical questions and usually cross several disciplines: protocol design, firmware, Linux, power electronics, debugging and user experience.', principles: [['Build to understand', 'Complex systems stop being black boxes when you bring them to the workbench.'], ['Design in layers', 'Hardware, protocol and application evolve better when their boundaries are explicit.'], ['Measure, fail, iterate', 'Every electrical failure or synchronization bug becomes reusable knowledge.']], toolbox: 'Toolbox', layers: 'Layers I work across', lab: 'Lab notes', small: 'Experiments and smaller projects', smallText: 'Academic work, prototypes and concepts that complement the main case studies.', next: 'Next system', closingA: 'From the first bit', closingB: 'to the final product.', closingText: 'Interested in firmware, embedded Linux, systems architecture and hardware challenges that demand looking beneath the abstraction.', back: 'Back to top', follow: 'Find me on', caseStudy: 'Case study', close: 'Close', concept: 'Concept render · replaceable with a real photo', detail: 'Detail', sections: ['What I built', 'Why I built it', 'Main challenge', 'What I learned'], hardware: 'Hardware', software: 'Software / stack', previous: 'Previous project', nextProject: 'Next project' },
};


function ProjectModal({ project, projectCount, locale, onClose, onPrevious, onNext }: { project: Project; projectCount: number; locale: Locale; onClose: () => void; onPrevious: () => void; onNext: () => void }) {
  const c = copy[locale];
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key === 'ArrowLeft') onPrevious(); if (event.key === 'ArrowRight') onNext(); };
    document.addEventListener('keydown', onKey); document.body.classList.add('modal-open');
    return () => { document.removeEventListener('keydown', onKey); document.body.classList.remove('modal-open'); };
  }, [onClose, onPrevious, onNext]);
  const sectionText = [project.built, project.why, project.challenge, project.learned];
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title"><button className="modal-close" type="button" onClick={onClose} aria-label={c.close} autoFocus>ESC <b>×</b></button><div className="modal-head"><div><p className="eyebrow">{c.caseStudy} / {project.id}</p><h2 id="project-modal-title">{project.name}</h2><p>{project.intro}</p></div><div className="modal-status"><span>{project.status}</span><span>{project.stack}</span><div className="modal-links">{project.repository && <a className="modal-external" href={project.repository} target="_blank" rel="noreferrer">{project.repository.includes('github.com') ? 'GitHub repo' : (locale === 'es' ? 'Proyecto / código' : 'Project / code')} ↗</a>}{project.url && project.url !== project.repository && <a className="modal-external" href={project.url} target="_blank" rel="noreferrer">{locale === 'es' ? 'Abrir proyecto' : 'Open project'} ↗</a>}</div></div></div><div className="project-gallery"><figure className="gallery-main"><img src={project.image} alt={`${locale === 'es' ? 'Imagen de' : 'Image of'} ${project.name}`} /><figcaption>{project.url ? (locale === 'es' ? 'Captura del proyecto' : 'Project screenshot') : c.concept}</figcaption></figure><figure className="gallery-crop crop-a"><img src={project.image} alt="" /><figcaption>{c.detail} / 01</figcaption></figure><figure className="gallery-crop crop-b"><img src={project.image} alt="" /><figcaption>{c.detail} / 02</figcaption></figure></div><div className="modal-content">{c.sections.map((title, index) => <div key={title}><span>0{index + 1} / {title}</span><p>{sectionText[index]}</p></div>)}</div><div className="modal-stack"><div><span>{c.hardware}</span>{project.hardware.map(item => <b key={item}>{item}</b>)}</div><div><span>{c.software}</span>{project.software.map(item => <b key={item}>{item}</b>)}</div></div><div className="modal-pagination"><button type="button" onClick={onPrevious}><span>←</span>{c.previous}</button><b>{project.id} / {String(projectCount).padStart(2, '0')}</b><button type="button" onClick={onNext}>{c.nextProject}<span>→</span></button></div></section></div>;
}

export default function Home() {
  const [locale, setLocale] = useState<Locale>('es');
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const [progress, setProgress] = useState(0);
  const [activeSection, setActiveSection] = useState('');
  const projects = getProjects(locale);
  const c = copy[locale];

  useEffect(() => {
    const queryLocale = new URLSearchParams(window.location.search).get('lang');
    const savedLocale = window.localStorage.getItem('portfolio-language');
    if (queryLocale === 'en' || queryLocale === 'es') setLocale(queryLocale);
    else if (savedLocale === 'en') setLocale('en');
  }, []);

  useEffect(() => {
    document.documentElement.lang = locale;
    document.title = locale === 'es' ? 'Mark Piazuelo — Sistemas embebidos y hardware' : 'Mark Piazuelo — Embedded Systems & Hardware';
    const onScroll = () => { const total = document.documentElement.scrollHeight - window.innerHeight; setProgress(total > 0 ? Math.min(100, (window.scrollY / total) * 100) : 0); };
    onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll);
  }, [locale]);

  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: '-30% 0px -60%' });
    ['work', 'about', 'experiments'].forEach(id => { const element = document.getElementById(id); if (element) observer.observe(element); });
    return () => observer.disconnect();
  }, []);

  const changeLocale = (nextLocale: Locale) => { setLocale(nextLocale); window.localStorage.setItem('portfolio-language', nextLocale); const url = new URL(window.location.href); if (nextLocale === 'en') url.searchParams.set('lang', 'en'); else url.searchParams.delete('lang'); window.history.replaceState({}, '', url); };
  const openWithKeyboard = (event: React.KeyboardEvent, index: number) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setActiveIndex(index); } };
  const previousProject = () => setActiveIndex(index => index === null ? 0 : (index + projects.length - 1) % projects.length);
  const nextProject = () => setActiveIndex(index => index === null ? 0 : (index + 1) % projects.length);
  const lead = projects[0];

  return <main>
    <div className="scroll-progress" style={{ width: `${progress}%` }} />
    <header className="nav-wrap"><nav className="nav shell" aria-label={locale === 'es' ? 'Navegación principal' : 'Main navigation'}><a className="brand" href="#top" aria-label="Home"><span className="brand-mark">MP</span><span>Mark Piazuelo</span></a><div className="nav-links"><a className={activeSection === 'work' ? 'active' : ''} href="#work">{c.projects}</a><a className={activeSection === 'about' ? 'active' : ''} href="#about">{c.profile}</a><a className={activeSection === 'experiments' ? 'active' : ''} href="#experiments">{c.experiments}</a></div><div className="nav-tools"><a className="nav-social" href="https://github.com/Mark19000" target="_blank" rel="noreferrer">GH↗</a><a className="nav-social" href="https://www.linkedin.com/in/mark-piazuelo/" target="_blank" rel="noreferrer">IN↗</a><div className="language-switch" aria-label="Language"><button className={locale === 'es' ? 'active' : ''} type="button" onClick={() => changeLocale('es')}>ES</button><span>/</span><button className={locale === 'en' ? 'active' : ''} type="button" onClick={() => changeLocale('en')}>EN</button></div><span className="status"><i /> {c.available}</span></div></nav></header>

    <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">{c.heroEyebrow}</p><h1>{c.heroA}<br /><em>{c.heroB}</em></h1><p className="lede">{c.lede}</p><div className="hero-actions"><a className="button primary" href="#work">{c.explore} <span>↓</span></a><a className="button secondary" href="#about">{c.about}</a></div></div><div className="system-map" aria-label="System map"><div className="map-head"><span>system_map.log</span><span>ACTIVE</span></div><div className="map-body"><div className="node hot"><small>01</small><strong>HARDWARE</strong><span>ESP32 · RP2040 · ARM</span></div><div className="connector"><span>SPI</span></div><div className="node"><small>02</small><strong>FIRMWARE</strong><span>C/C++ · Drivers · RTOS</span></div><div className="connector"><span>API</span></div><div className="node"><small>03</small><strong>SYSTEM</strong><span>Linux · Protocols · UI</span></div></div><div className="map-foot"><span>latency: low</span><span>layers: 03</span><span>status: building</span></div></div></section>

    <section className="focus-strip"><div className="shell focus-list">{focus[locale].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}</div></section>
    <section className="work shell" id="work"><div className="section-heading"><div><p className="eyebrow">{c.selected}</p><h2>{c.featured}</h2></div><p>{c.featuredText}</p></div><article className="project-card project-lead is-clickable" role="button" tabIndex={0} aria-haspopup="dialog" onClick={() => setActiveIndex(0)} onKeyDown={event => openWithKeyboard(event, 0)}><div className="project-number">{lead.id} / {String(projects.length).padStart(2, '0')}</div><div className="project-copy"><div className="project-meta"><span>{lead.status}</span><span>{lead.stack}</span></div><p className="project-label">{lead.label}</p><h3>{lead.name}</h3><p className="project-tagline">{lead.intro}</p><p>{lead.body}</p><span className="project-link">{c.open} <b>↗</b></span></div><div className="project-visual project-image"><img src={lead.image} alt={lead.name} /><span className="concept-badge">Concept render</span></div></article><div className="project-stack">{projects.slice(1).map((project, sliceIndex) => { const index = sliceIndex + 1; return <article className="project-row is-clickable" role="button" tabIndex={0} aria-haspopup="dialog" onClick={() => setActiveIndex(index)} onKeyDown={event => openWithKeyboard(event, index)} key={project.slug}><div className="project-number">{project.id} / {String(projects.length).padStart(2, '0')}</div><div className="project-copy"><div className="project-meta"><span>{project.status}</span><span>{project.stack}</span></div><p className="project-label">{project.label}</p><h3>{project.name}</h3><p className="project-tagline">{project.intro}</p><p>{project.body}</p><span className="project-link">{c.open} <b>↗</b></span></div><div className="project-visual project-image"><img src={project.image} alt={project.name} /><span className="concept-badge">{project.url ? (locale === 'es' ? 'Captura del proyecto' : 'Project screenshot') : 'Concept render'}</span></div></article>; })}</div></section>

    <section className="about" id="about"><div className="shell about-grid"><div><p className="eyebrow">{c.profileEye}</p><h2>{c.profileA}<br />{c.profileB}</h2></div><div className="about-copy"><p className="about-lede">{c.aboutLead}</p><p>{c.aboutP1}</p><p>{c.aboutP2}</p></div><div className="principles">{c.principles.map(([title, text], index) => <div key={title}><span>0{index + 1}</span><b>{title}</b><p>{text}</p></div>)}</div></div></section>
    <section className="toolbox shell"><div className="section-heading"><div><p className="eyebrow">{c.toolbox}</p><h2>{c.layers}</h2></div></div><div className="tool-grid"><div><span>01</span><h3>Hardware</h3><p>ESP32 / ESP32-S3<br />RP2040 / Raspberry Pi<br />Arduino · ARM64</p></div><div><span>02</span><h3>Interfaces</h3><p>SPI · I²C · UART<br />PWM · ADC · GPIO<br />Custom protocols</p></div><div><span>03</span><h3>Software</h3><p>C · C++ · Python<br />ESP-IDF · Pico SDK<br />MicroPython · LVGL</p></div><div><span>04</span><h3>Systems</h3><p>Linux · CMake · Git<br />OpenOCD · Docker<br />VHDL · Quartus</p></div></div></section>
    <section className="experiments shell" id="experiments"><div className="section-heading"><div><p className="eyebrow">{c.lab}</p><h2>{c.small}</h2></div><p>{c.smallText}</p></div><div className="experiment-list">{experiments[locale].map(([name, stack], index) => <div key={name}><span>{String(index + 1).padStart(2, '0')}</span><h3>{name}</h3><p>{stack}</p><i>↗</i></div>)}</div></section>

    <section className="social-band"><div className="shell"><span>{c.follow}</span><a href="https://github.com/Mark19000" target="_blank" rel="noreferrer"><b>GitHub</b><i>↗</i></a><a href="https://www.linkedin.com/in/mark-piazuelo/" target="_blank" rel="noreferrer"><b>LinkedIn</b><i>↗</i></a></div></section>
    <section className="closing shell"><p className="eyebrow">{c.next}</p><h2>{c.closingA}<br />{c.closingB}</h2><p>{c.closingText}</p><div className="closing-actions"><a className="button primary" href="https://www.linkedin.com/in/mark-piazuelo/" target="_blank" rel="noreferrer">LinkedIn <span>↗</span></a><a className="button secondary" href="#top">{c.back} <span>↑</span></a></div></section><footer className="footer shell"><span>© 2026 Mark Piazuelo</span><span>Embedded systems · Barcelona, ES</span><a href="https://github.com/Mark19000" target="_blank" rel="noreferrer">github.com/Mark19000 ↗</a></footer>
    {activeIndex !== null && <ProjectModal project={projects[activeIndex]} projectCount={projects.length} locale={locale} onClose={() => setActiveIndex(null)} onPrevious={previousProject} onNext={nextProject} />}
  </main>;
}
